<?php
/**
 * @file
 * Bower Manager module.
 */

/**
 * Implements hook_modules_enabled().
 */
function bower_manager_modules_enabled($modules) {
  bower_manager_update($modules);
}

/**
 * Scan the passed (or all enabled) modules for bower.json files.
 *
 * @param mixed $modules
 *   An array of module names or a single module name as string.
 */
function bower_manager_update($modules = NULL) {
  // Check if a bower.json file exists in the default theme.
  $target_file = drupal_get_path('theme', variable_get('theme_default')) . '/bower.json';
  if (!is_file($target_file)) {
    return;
  }

  // Get moodule names from drush option.
  if ($option_modules = drush_get_option('modules', NULL)) {
    $modules = explode(',', $option_modules);
  }

  // Scan in all modules if no modules are specified.
  if (!isset($modules)) {
    $modules = module_list();
  }

  $modules = is_array($modules) ? $modules : array($modules);
  // Scan modules for bower.json files.
  foreach ($modules as $module) {
    $source_file = drupal_get_path('module', $module) . '/bower.json';
    if (is_file($source_file)) {
      _bower_manager_update_extend_file($source_file, $target_file);
    }
  }
}

/**
 * Merge bower dependencies of a source bower.json file into a target.json file.
 *
 * @param string $source_file
 *   Path to the source bower.json.
 * @param string $target_file
 *   Path to the target bower.json.
 */
function _bower_manager_update_extend_file($source_file, $target_file) {
  $source_json_array = json_decode(file_get_contents($source_file), TRUE);
  $target_json_array = json_decode(file_get_contents($target_file), TRUE);

  $target_json_array['dependencies'] = array_merge($target_json_array['dependencies'], $source_json_array['dependencies']);
  ksort($target_json_array['dependencies']);

  $target_json = json_encode($target_json_array, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);
  // Convert four spaces indentation to two spaces indentation.
  $target_json = str_replace(array('    ', '|tab|'), array('|tab|', '  '), $target_json);

  file_put_contents($target_file, $target_json . "\r\n");
}
